BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBBBBBBBBBB BBBB BBBBBBBBBBBBBB
BBBB BBBB


BBBBB BBBBBBBBBBXXXXXXXXXXXBBBBBBBB

BBBBB BBBBBBBBBBXXXXBBBBBBBB

BBBBB BBBBBBBBB
    XXXXXXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            BBBBBBB BBBBBBBBBBBBBBBB
            BBB BBBBBBBB BB BBBBBBBBBB
            XXXXXX XXXXXXBBB BBBBBBXXXXXXXXXXX
            XXX
                 gettext('\n                ') 
                
            XXXX
            BB BBB BBBBBBBBBBBBBBBBBBBBB
            BBB BBBBBBBBBBBBBBB BB BBBBBBBBB
            BBB BBBBBBBBBBBBBBBB BB BBBBBBBBBB
            BBBBB
        XXXXXX
    XXXXXXXXXX
    XXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXX
        XXXXXXX
            XXXX
                XXXXXXX gettext(' <b>专业 学校 Institution</b>')  SSSSS SS SSSSSSSSSSSSSSSXXXXXXXXX
                XXXXXXX gettext(' <b>城市 City</b>')  SSSSS SSSSSSSSXXXXXXXXX
                XXXX XXX gettext(' <b>课程 Course Name</b>')  SSSSS SSSSSS SSSSSSSSXXXXXXXXX
                XXXX XXX gettext(' <b>老师日记</b>')  SSSSSSSSSSSXXXXXXXXX
            XXXXX
        XXXXXXXX
        XXXXXXX
        BBB BBBBBB BB BBBBBBBBBB
            XXXX
                XXXXXXXXX
                XXXXXXXXX
                XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBB BBBBBBBBBXXXXXXXXXXX
                XXXXXXXXXXX
            XXXXX
         BBBBB
            XXXX
                XXXXXXXXX
                XXXXXXXXX
                XXXXXXXXX
                XXXXXXXXX
            XXXXX
        BBBBBB
        XXXXXXXX
        XXXXXXXX
        XXXXXX
    XXXXXXXXXX
        XXXXXXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXX
                XXXXX
                    XXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBXXXX XXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX
                     XX XXXXXXXXXXXXXXXXXXX
                XXXXXX
                XXXXX
                    XXXXX XXXXXXBBB BBBBBBXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                XXXXXX
                XXXXX
                    XXXXX XXXXXXBBB BBBBBBXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                XXXXX
                    XXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXXXXXX
    XXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXX XXXXXXXXXXXXX
                 gettext('\n                ') 
                
            XXXX
        XXXXXX
    XXXXXXXXXX
BBBBBBBB