BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBBBBBXXXXXXXXXXXBBBBBBBB

BBBBB BBBBBBBBBBXXXXXXBBBBBBBB

BBBBB BBBBBBBBB
    XXXXXXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXX
            XXXXXXX
                XXXX
                    XXXXXXX gettext(' <b>专业 学校 Institution</b>')  SSSSS SS SSSSSSSSSSSSSSSXXXXXXXXX
                    XXXXXXX gettext(' <b>城市 City</b>')  SSSSS SSSSSSSSXXXXXXXXX
                    XXXX XXX gettext(' <b>课程 Course Name</b>')  SSSSS SSSSSS SSSSSSSSXXXXXXXXX
                    XXXX XXX gettext(' <b>老师日记</b>')  SSSSSSSSSSSXXXXXXXXX
                XXXXX
            XXXXXXXX
            XXXXXXX
            BBB BBBBBB BB BBBBBBBBBB
                XXXX
                    XXXXXXXXX
                    XXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXX
                    XXXXXXXXXXX
                XXXXX
             BBBBB
                XXXX
                    XXXXXXXXX
                    XXXXXXXXX
                    XXXXXXXXX
                    XXXXXXXXX
                XXXXX
            BBBBBB
            XXXXXXXX
            XXXXXXXX
            XXXXXX
        XXXXXX
    XXXXXXXXXX
    XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXX XXXXXXXXXXX
        XXXXXXX
            
            XXXX
                XXXXXXXXXXXXXXX
                XXXX
                    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
                XXXXX
            XXXXX
        XXXXXXXX

        BB BBBBB
            XXXXXXXXXXXXXXXX

            BBB BBBBBB BB BBBBBBBBBBBBBBBB
                XXX
                    XX XXXXXXXXXXXX
                XXXX
            BBBBB
                XXXXX XXXXXXX XXXXXXXXXX
            BBBBBB

            BB BBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBB
                XXXXX
                    BB BBBBBBBBBBBBBBBBBXX XXXXXXXXXXXXXXXXXXXXXBBBBBXXXXXXX XXXXXXXXBB BBBBBBBBBBBBBBBBBXXXXBBBBB
                    X
                    BB BBBBBBBBBBBBBXX XXXXXXXXXXXXXXXXXXXXXBBBBBXXXX XXXXXXXBB BBBBBBBBBBBBBXXXXBBBBB
                XXXXXX
            BBBBB
        BBBB
            
        BBBBB
    XXXXXXX
    XXXXXX
    XXXXXXXXXX
            XXXXXXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXX
                XXXXX
                    XXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBXXXX XXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX
                     XX XXXXXXXXXXXXXXXXXXX
                XXXXXX
                XXXXX
                    XXXXX XXXXXXBBB BBBBBBXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                XXXXXX
                XXXXX
                    XXXXX XXXXXXBBB BBBBBBXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                XXXXX
                    XXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXXXXXX
BBBBBBBB