BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBBBBBBBBBB BBBB BBBBBBBBBBBBBB
BBBB BBBB


BBBBB BBBBBBBBBBXXXXXXXXXXXBBBBBBBB

BBBBB BBBBBBBBBBXXXXBBBBBBBB

BBBBB BBBBBBBBB
    XXXXXXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            BBBBBBB BBBBBBBBBBBBBBBB
            BBB BBBBBBBBBBBBB BB BBBBBBBBBBBBBBB
            XXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBXXXXXXXXXXXXXXX
            BB BBB BBBBBBBBBBBBBBBBBBBBB
            BBB BBBBBBBBBBBBBBB BB BBBBBBBBB
            BBB BBBBBBBBBBBBBBBB BB BBBBBBBBBB
            BBBBB
        XXXXXX
    XXXXXXXXXX
        XXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXX XXXXXXXXXXXXX
                XXXXXXX XXXX XXXXXX XXXXXXXXXXX
            XXXX
        XXXXXX
    XXXXXXXXXX
    XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXX
        XXXXXXX
            XXXX
                XXXXXXX gettext(' <b>专业编号 Course Code</b>')  SSSSSSS SSSSSS SSSSSSSSXXXXXXXXX
                XXXXXXX gettext(' <b>专业开学 Course Start Date</b>')  SSSSSSS SSSSSS SSSSS SSSSSSSSXXXXXXXXX
                XXXXXXX gettext(' <b>申请截止 Application Deadline</b>')  SSSSSSS SSSSSSSSSSS SSSSSSSSSSSSXXXXXXXXX
                XXXXXXX gettext(' <b>专科部门 Faculty Name</b>')  SSSSSSS SSSSSSS SSSSSSSSXXXXXXXXX
            XXXXX
        XXXXXXXX
        XXXXXXX
            XXXX
                XXXXXXXXX
                XXXXXXXXX
                XXXXXXXXX
                XXXXXXXXX
            XXXXX
        XXXXXXXX
        XXXXXXXX
            XXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXX
        XXXXXXX
            XXXX
                XXXXXXX gettext(' <b>学费 Fees</b>')  SSSSS SSSSSSSSXXXXXXXXX
                XXXXXXX gettext(' <b>学期期间 Duration</b>')  SSSSSSS SSSSSSSSSSSSXXXXXXXXX
                XXXX XXX gettext(' <b>2016 课程内容 2016 Course Structure</b>')  SSSSSSS SSSS SSSS SSSSSS SSSSSSSSSSSSSXXXXXXXXX
                XXXX XXX gettext(' <b></b>')  SSSSSSSXXXXXXXXX
            XXXXX
        XXXXXXXX
        XXXXXXX
            XXXX
                XXXXXXXXX
                XXXXXXXXX
                XXXXXX XXXXXXXXXXXX
                XXXXXXXXX
            XXXXX
        XXXXXXXX
        XXXXXXXX
    XXXXXX
    XXXXXXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                BBB BBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBB
                XXXXX
                    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBB BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBXX
                        XXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        XXX XXXX XXXXXX XXXXXXXXXX
                XXXXXX
                BBBBB
                XXXXX
                    XXXXXXXXXXX
                     gettext('\n                    <b><br></b> <br>\n                    ') 
                    SSSSSSSSSSS SSSS
                    
                XXXXXX
                BBBBBB
            XXXXXX
        XXXXXX
    XXXXXXXXXX
        XXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXX
                XXXXX
                    XXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBXXXX XXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX
                     XX XXXXXXXXXXXXXXXXXXX
                XXXXXX
                XXXXX
                    XXXXX XXXXXXBBB BBBBBBXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                XXXXXX
                XXXXX
                    XXXXX XXXXXXBBB BBBBBBXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                XXXXX
                    XXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXXXXXX
    XXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXX XXXXXXXXXXXXX
                 gettext('\n                ') 
                
            XXXX
        XXXXXX
    XXXXXXXXXX
BBBBBBBB
